### ISSUE TITLE
Verification by bot

### ISSUE THREAD

**Issue by Anubhav1603** [wpmjones/apibot#2]
When someone joins the server and provided us the information in which language they code bot should add role +edit their nickname with `!verify @user language` 

Whom do you want to work on ;
- [x] I want to add this feature myself
- [ ] Anyone can add this feature

**Comment by wpmjones** [comment]
We've talked about this a few times with the guys that admin the server.  We even thought about automating it so that the bot asked specific questions and if certain words appeared in the response, the bot would add the roles without a need for a command.  But at the end of it, we decided that we had two issues.

A) We want there to be some human interaction with new guests.  We do not want to be so impersonal that a computer does all of the welcoming.
B) If we give users the ability to add roles and nicknames, there may be some abuse and we're not at a point - scale wise - that we need it to be automated.  If we were dealing with 1000 plus users, we might look to automate it, but for now. we're happy to have the conversation, then make the changes ourselves.
